version: '3.7'
services:

  ## MySQL Initialization Volume
  # Place create_user.sql inside ./mysql-init folder
  # with content to create 'sahil' user and grant privileges to all DBs

  ## MySQL for Product-Inventory Service
  mysql-product:
    container_name: mysql-product-inventory
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Sahil@123"
      MYSQL_DATABASE: products_inventory_db
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-product:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  ## MySQL for Cart Service
  mysql-cart:
    container_name: mysql-cart
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Sahil@123"
      MYSQL_DATABASE: carts_db
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-cart:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  ## MySQL for Orders Service
  mysql-order:
    container_name: mysql-order
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Sahil@123"
      MYSQL_DATABASE: orders_db
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-order:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  ## MySQL for User Service
  mysql-user:
    container_name: mysql-user
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Sahil@123"
      MYSQL_DATABASE: users_db
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    ports:
      - "3310:3306"
    volumes:
      - ./mysql-user:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  ## MySQL for Payments Service
  mysql-payments:
    container_name: mysql-payments
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Sahil@123"
      MYSQL_DATABASE: payments_db
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    ports:
      - "3311:3306"
    volumes:
      - ./mysql-payments:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  ## Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  ## Eureka Server
  service-registry:
    image: service-registry:0.0.1-SNAPSHOT
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  ## API Gateway
  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: api-gateway
    ports:
      - "9000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-registry
      - zipkin

  ## Product-Inventory Service
  product-inventory-service:
    image: product-inventory-service:0.0.1-SNAPSHOT
    container_name: product-inventory-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-product:3306/products_inventory_db
      - SPRING_DATASOURCE_USERNAME=sahil
      - SPRING_DATASOURCE_PASSWORD=Sahil@123
    depends_on:
      - mysql-product
      - service-registry
      - gateway

  ## Cart Service
  cart-service:
    image: cart-service:0.0.1-SNAPSHOT
    container_name: cart-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-cart:3306/carts_db
      - SPRING_DATASOURCE_USERNAME=sahil
      - SPRING_DATASOURCE_PASSWORD=Sahil@123
    depends_on:
      - mysql-cart
      - service-registry
      - gateway

  ## Orders Service
  orders-service:
    image: orders-service:0.0.1-SNAPSHOT
    container_name: orders-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3306/orders_db
      - SPRING_DATASOURCE_USERNAME=sahil
      - SPRING_DATASOURCE_PASSWORD=Sahil@123
    depends_on:
      - mysql-order
      - service-registry
      - gateway

  ## User Service
  user-service:
    image: user-service:0.0.1-SNAPSHOT
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/users_db
      - SPRING_DATASOURCE_USERNAME=sahil
      - SPRING_DATASOURCE_PASSWORD=Sahil@123
    depends_on:
      - mysql-user
      - service-registry
      - gateway

  ## Auth Service
  auth-service:
    image: auth-service:0.0.1-SNAPSHOT
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - USER_SERVICE_URL=http://user-service:8080
    depends_on:
      - user-service
      - service-registry
      - gateway

  ## Payments Service
  payments-service:
    image: payments-service:0.0.1-SNAPSHOT
    container_name: payments-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-payments:3306/payments_db
      - SPRING_DATASOURCE_USERNAME=sahil
      - SPRING_DATASOURCE_PASSWORD=Sahil@123
    depends_on:
      - mysql-payments
      - service-registry
      - gateway
